apiVersion: apps/v1
kind: Deployment
metadata:
  name: testing
  namespace: argocd
spec:
  selector:
    matchLabels:
      app: testing
  template:
    metadata:
      labels:
        app: testing
    spec:
      containers:
        - name: "testing"
          image: oluwaseun7/testing-docker:1.1.1 
          imagePullPolicy: Always
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
          - containerPort: 80