apiVersion: apps/v1
kind: Deployment
metadata:
  name: testings
  namespace: argocd
spec:
  selector:
    matchLabels:
      app: testings
  template:
    metadata:
      labels:
        app: testings
    spec:
      containers:
        - name: "testings"
          image: oluwaseun7/testings-docker:1.2.1 
          imagePullPolicy: Always
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
          - containerPort: 80